export const SET_LICH_CHIEU_THEO_HE_THONG_RAP =
  "SET_LICH_CHIEU_THEO_HE_THONG_RAP";
export const SET_THONG_TIN_LICH_CHIEU_PHIM = "SET_THONG_TIN_LICH_CHIEU_PHIM";
export const SET_THONG_TIN_LICH_CHIEU_PHIM_BOOKING_BAR = "SET_THONG_TIN_LICH_CHIEU_PHIM_BOOKING_BAR";
export const SET_THONG_TIN_HE_THONG_RAP = "SET_THONG_TIN_HE_THONG_RAP"; 
export const SET_THONG_TIN_CUM_RAP_THEO_HE_THONG = "SET_THONG_TIN_CUM_RAP_THEO_HE_THONG"; 