export const DANG_NHAP = "DANG_NHAP";
export const DANG_KY = "DANG_KY";
export const SET_THONG_TIN_NGUOI_DUNG_TIM_KIEM =
  "SET_THONG_TIN_NGUOI_DUNG_TIM_KIEM";
export const SET_THONG_TIN_TAI_KHOAN = "SET_THONG_TIN_TAI_KHOAN";
export const SET_THONG_TIN_NGUOI_DUNG = "SET_THONG_TIN_NGUOI_DUNG";
export const SET_DANH_SACH_NGUOI_DUNG = "SET_DANH_SACH_NGUOI_DUNG";
export const SET_DANH_SACH_LOAI_NGUOI_DUNG = "SET_DANH_SACH_LOAI_NGUOI_DUNG";
